version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www/html
      - ./config/config/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./config/nginx/task.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/var/www/html

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
